#!/usr/bin/env python3
"""Build the frozen native-fidelity ledger for the main F/T census.

This is a static evidence crosswalk.  It does not install, import, or execute
third-party artifacts.  A system is common-task compatible only if the public
materials ship native dated outputs with timing and identifiers sufficient for
the prespecified six-country monthly JKP evaluator without replacing the
system's core mechanism.
"""
from __future__ import annotations

import csv
from pathlib import Path
import re


ROOT = Path(__file__).resolve().parents[1]
CENSUS = ROOT / "literature_review" / "census_v1" / "system_registry.csv"
AUDIT = (
    ROOT
    / "paper_runs"
    / "submission_evidence"
    / "artifact_audit"
    / "artifact_audit.csv"
)
OUTPUT = (
    ROOT
    / "paper_runs"
    / "submission_evidence"
    / "native_fidelity_ledger.csv"
)
EXPECTED_FT = 67
URL_RE = re.compile(r"https?://[^;\s]+")


# Static observations are pinned to the immutable heads recorded in the
# artifact audit.  "Output" below means an output generated by the named
# system, not raw inputs, prompts, labels, factor expressions, or example
# configuration.
ARTIFACT_NOTES = {
    "SYS-ALPHA-AGENT": (
        "N",
        "A pinned arXiv-v2 audit enumerates all 106 numeric cells in Tables 1--2: "
        "100 results and 6 trading-day configurations, plus 18 quantitative result "
        "claims in figures/text. The official Git history begins in July 2026, more "
        "than a year after the paper, and implements a different CSI1000/Tushare "
        "framework. Its 80 tests pass with import-only dependency stubs and four "
        "named base factors execute deterministically on synthetic data, but these "
        "are post-paper components. The source lacks the paper's three agents, AST "
        "subtree originality, regularizers, LightGBM/Qlib portfolio, baselines, "
        "prompts, trials, factors, and outputs. The linked 2026 data package has the "
        "wrong markets, source, and vintage, so 0/100 table result cells count as "
        "native reproductions.",
    ),
    "SYS-ALPHA-MEMO": (
        "N",
        "A pinned arXiv-v1 audit enumerates all 484 numeric experimental cells in "
        "Tables 2--9: 474 results and 10 configuration cells. The official test and "
        "a deterministic native synthetic smoke run pass, and the native parser can "
        "execute all five published formulas on synthetic arrays. These are components, "
        "not paper outputs. No Qlib data snapshot, search trajectory, factor pool, "
        "prediction, return, or table output is shipped, so 0/474 result cells count as "
        "native reproductions. The active runner's ICIR threshold is 0.02 versus the "
        "paper's 0.10, and source motif/context/gating behavior differs from the paper.",
    ),
    "SYS-ALPHA-R1": (
        "N",
        "A pinned arXiv-v1 audit enumerates all 652 displayed numeric result "
        "cells: 124 cells in Tables 1--3 and 528 cells in six heatmaps, plus "
        "27 quantitative result claims in prose. The paper says the full "
        "implementation and resources are available, but the only paper-era "
        "revision is a two-line title README and the current three-commit "
        "history still contains only one README marking inference code and "
        "model weights Coming Soon. No code, environment, prompts, checkpoint, "
        "market/news data, factor lists, betas, baselines, seeds, paths, or "
        "outputs are shipped, so 0/652 table/heatmap cells and 0/70 audited "
        "implementation dimensions count as native reproductions. The local "
        "M0 narrative motif proxy remains secondary and receives no paper-result "
        "or mechanism credit.",
    ),
    "SYS-AUTOMATE-STRATEGY": (
        "Y",
        "The snapshot bundles seven 2022Q4 individual-factor analysis workbooks "
        "with IC summaries and quantile-return/turnover series, plus prompt logs. "
        "It does not ship the integrated 2023 portfolio path behind paper Table 4, "
        "and the factor outputs are not a six-country security-level signal panel.",
    ),
    "SYS-QUANTA-ALPHA": (
        "N",
        "A pinned three-revision paper audit enumerates 344 numeric result table "
        "cells, 40 labeled figure/diagram values, 47 discrete unlabeled marker "
        "points, and 10 raster return curves. The official release is substantial: "
        "all 135 Python files in both the initial and current revisions compile, "
        "and dependency-isolated native AST, trajectory persistence, lineage, and "
        "crossover-selection components execute. These are architecture components, "
        "not paper results. The checked-in experiment and mining-loop configs conflict "
        "with the paper, claimed trajectory-segment repair/splicing is not structurally "
        "implemented, and the sole upstream test fails because its template is absent. "
        "No approximately-150-factor pool, trajectories, exact model/API runs, baselines, "
        "seeds, predictions, portfolios, returns, or plot arrays are shipped, so 0/344 "
        "table cells count as native reproductions. Large v1/v2-to-v3 result revisions "
        "lack released lineage, and v3 contains direct figure/prose inconsistencies.",
    ),
    "SYS-QUANT-EVOLVER": (
        "N",
        "A pinned arXiv-v1 audit enumerates all 75 numeric result cells in the two "
        "paper tables plus 31 quantitative result assertions in prose/figures. The "
        "paper-era release is a substantial framework: all 55 Python files compile, "
        "all three upstream tests pass, three released example seeds and a nine-task "
        "example bank execute deterministically, and 38/67 mechanism dimensions "
        "match or have meaningful analogues. These are components, not the paper "
        "experiment. The README explicitly excludes private market data, trained "
        "checkpoints, experiment logs, and paper-specific reproduction scripts; no "
        "paper factors, baselines, fusion arrays, trials, seeds, or costs are shipped, "
        "so 0/75 table cells count as native reproductions. The separate 3/3 grade-B "
        "component gate remains adapted and provides no paper-result credit.",
    ),
    "SYS-GPT-SIGNAL": (
        "Y",
        "A pinned arXiv-v1/ACL-final audit recovers an author-owned pre-publication "
        "thesis repository containing 13,884 tracked files: the exact 93-company "
        "FactSet workbooks, cached Yahoo price inputs, 16 GPT-4 output CSVs, figures, "
        "and analysis code. A deterministic source-semantics replay regenerates all "
        "1,309 published heatmap cells and 240/245 boxplot statistics, or "
        "1,549/1,554 published quantitative units. This is strong author-data result "
        "lineage, not an end-to-end GPT regeneration: the recovered "
        "gpt-4-1106-preview snapshot is retired, no seed or temperature is recorded, "
        "and one of six signals lacks raw GPT output. The printed RAPS equation "
        "conflicts with the GPT output, code, and results; all five all-sector EVC "
        "box statistics contain an unexplained +0.02 shift. More importantly, the "
        "one-month panels use future-quarter fundamentals because descending "
        "workbooks are forward-filled without sorting, and full-period mean "
        "imputation adds another lookahead path. The current runner exits before "
        "step 2, has a stale monthly loop length, and ships no dependency lock, "
        "license, portfolio, costs, or significance evaluation. Its dated outputs "
        "cover a fixed U.S. universe and cannot supply the prespecified six-country "
        "security-level common-task panel.",
    ),
    "SYS-RAPTOR": (
        "Y",
        "A pinned CEUR/OpenReview audit inventories all 42 empirical scalar "
        "assertion/table units and three figure series. The published PDF directly "
        "links the lead author's Apache-2.0 repository; a separately pinned GitHub "
        "copy is a high-confidence double-blind derivative with 815 byte-identical "
        "files. The release ships 166 dated portfolio snapshots. Its native "
        "postprocessor runs, and those snapshots independently recover 16/42 scalar "
        "units, including the initial/final NAV, total and annualized return, "
        "volatility, Sharpe, Sortino, and maximum drawdown. This is author-output "
        "verification, not experiment reproduction: 0/42 result units and 0/3 exact "
        "figure series reproduce end to end. The candidate backtest stops on the "
        "missing testing/stock_prices.csv; SPY inputs, point-in-time research inputs, "
        "immutable model requests, seeds, and execution-cost lineage are absent, "
        "while paper/source cadence, view construction, and rolling-Sharpe conventions "
        "conflict. The shipped path is U.S.-only and cannot supply the six-country "
        "security-level common-task panel.",
    ),
    "SYS-RD-AGENT-QUANT": (
        "N",
        "The mapped primary record is the general R&D-Agent MLE-Bench report, not "
        "the separate quant paper. A pinned audit inventories 534 displayed numeric "
        "cells (526 unique measurements) and 24 result-figure series/bars, with zero "
        "native results reproduced. All 21 audited mechanisms have identifiable "
        "paper-era source components, but no run configs, traces, frozen Kaggle/MLE-"
        "Bench data, model snapshots, seeds, submissions, or checkpoints prove which "
        "non-default alternatives generated the paper results; advertised trace links "
        "are broken. Component compilation/execution receives no result credit.",
    ),
    "SYS-ALPHA-QUANTER": (
        "N",
        "A pinned paper audit checks all 790 numeric cells in Tables 5--8 and "
        "10--14. The release ships 2,615 training/validation prompt-label rows: "
        "a current Yahoo retrieval reproduces 523 labels exactly and 2,612 reward "
        "regimes. A released-semantics market-baseline reconstruction matches 1/34 "
        "repeated Buy-and-Hold cells at display precision. These are components, "
        "not agent outputs; all 756 non-market cells lack checkpoints, actions, "
        "three-seed paths, logs, or human ratings, and the paper test split is absent.",
    ),
    "SYS-CONTEST-TRADE": (
        "N",
        "A pinned arXiv-v4 audit enumerates all 49 numeric cells in Tables 1--3. "
        "The released CLI runs a three-node agent graph that never calls either "
        "paper contest and does not construct the Sharpe-weighted portfolio. The "
        "isolated Research Contest lacks both required models and a method it calls; "
        "the isolated Data Contest ships two fixed models without rolling-training "
        "provenance, uses top-3 sorting rather than facility-location allocation, and "
        "changes the paper's signed ZI sum into a clipped positive-only average. No "
        "native inputs, outputs, evaluator, baselines, ablations, or seeds are shipped, "
        "so zero paper result cells count as native reproductions.",
    ),
    "SYS-CRYPTO-TRADE": (
        "Y",
        "The README ships a dated one-step ETH action/ROI example. A pinned paper-level "
        "audit additionally recomputes 174/180 displayed deterministic traditional-baseline "
        "cells (43/45 complete rows) from the native crypto data and environment, but no "
        "full-period LLM or time-series result paths are shipped. The evidence remains "
        "crypto rather than six-country equity output.",
    ),
    "SYS-FIN-CON": (
        "N",
        "A pinned NeurIPS-final paper audit inventories 306 displayed numeric cells "
        "(288 unique measurements) and 106 raster result series, with zero native "
        "results reproduced. Every one of the official repository's 11 commits "
        "contains only README.md: no FinCon code, prompts, configs, data, models, "
        "tests, raw trajectories, or plot inputs are released. The arXiv LaTeX "
        "compiles, but paper packaging receives no system or result credit.",
    ),
    "SYS-FIN-AGENT": (
        "N",
        "A pinned KDD/arXiv-v3 audit inventories all 959 displayed numeric table "
        "cells and 102 figure result units, with zero native results reproduced. "
        "The author-linked MIT release is substantial: the paper-era tree has 341 "
        "files, all 142 Python files compile, 42 experiment configs retain the core "
        "dates/horizons/assets, and the LaTeX source reproduces the 43-page paper. "
        "These are static implementation and document evidence, not experiment "
        "outputs. No exact data snapshot, FinAgent memories, trajectories, actions, "
        "equity paths, or result records are shipped. The full validation chart path "
        "renders 14 future days, the environment is long-only despite the paper's "
        "short-position explanation, optimized rule signals are overwritten, six "
        "ML/RL baselines and OPTUNA are absent, and SR/CR/SOR code conflicts with "
        "the paper equations.",
    ),
    "SYS-EMPIRICAL-ASSET-PRICING-LLM": (
        "N",
        "A pinned two-version AAPM audit inventories 114 v1 and 162 v2 table "
        "cells plus 54 quantitative figure units, with zero native paper results "
        "reproduced. Both official arXiv source versions directly link the MIT "
        "repository. Its ten tracked files include five Python components, a config, "
        "requirements, and 65,733 WSJ metadata records; all Python files compile. "
        "This is static component evidence, not experiment output. Article bodies, "
        "CRSP returns, manual factors, report embeddings, checkpoints, baselines, "
        "portfolio/pricing evaluators, sweep histories, and result arrays are absent. "
        "The model never ingests the paper's central manual-factor input or performs "
        "historical-factor pretraining, model.py has no training entrypoint, the macro "
        "note stores an unexecuted update prompt, and evaluation/checkpoint/seed paths "
        "are defective. The v2 code lineage is not demonstrated: current code differs "
        "from the 2024 paper-era tree only in README, still uses GPT-3.5, and released "
        "metadata ends 2023-11-30 rather than the claimed 2024-09-29 endpoint. In the "
        "paper sources, 112/114 common table cells change while 15/16 rasters are reused.",
    ),
    "SYS-FIN-MEM": (
        "N",
        "A pinned paper audit recomputes 16/40 repeated Buy-and-Hold metric cells "
        "from the released formula and a current Yahoo snapshot, including both full "
        "TSLA ablation rows. All 195 non-Buy-and-Hold cells remain unverifiable: the "
        "release ships fake/sample inputs but no native action paths, checkpoints, or "
        "five-trial outputs, and its sole config differs from the paper.",
    ),
    "SYS-HEDGE-AGENTS": (
        "N",
        "A pinned HedgeAgents audit inventories all 236 displayed numeric table "
        "cells: 119 in the main table, 63 in the conference ablation, and 54 in "
        "the LLM-backbone table. The author repository is a 46-file R1 static site, "
        "not a trading implementation. Its leaderboard duplicates 90 main-table "
        "cells exactly, and four profile screenshots expose 23 unique tool names "
        "and ten unique action names, but these are author documentation rather "
        "than native execution: 0/236 cells reproduce. The site also contains an "
        "unrelated 6,141-record MathVista/VQA template that receives no HedgeAgents "
        "data or code credit. No exact universe, frozen Yahoo/Alpaca inputs, full "
        "prompts, tool implementations, LLM traces, memories, actions, orders, "
        "fills, or dated portfolio path is released. The paper conflicts on the "
        "full-system MDD, per-agent tool/action counts, Sharpe improvements, and "
        "all-metrics superiority. Its 2021--2023 test also mostly lies inside the "
        "official April 2023 knowledge horizon of gpt-4-1106-preview; a later paper "
        "by the same authors makes this a material contamination risk, not direct "
        "proof that any reported cell is false.",
    ),
    "SYS-FIN-RL-DEEPSEEK": (
        "N",
        "A pinned arXiv-v1 audit checks all 36 displayed table cells (24 unique "
        "measurements), 32 raster return series, and 4 raster IR labels. The public "
        "paper-era release is substantial: frozen train/trade CSVs, 15 checkpoints, "
        "training logs, and backtest code are available, and all eight table-relevant "
        "checkpoints execute on the released CSVs under three audited evaluation "
        "protocols. But 0/36 paper table cells and 0/32 figure series receive result "
        "credit. The stored notebook has 27/36 values, none matching the paper, and "
        "reports six conflicting values for repeated identical series. Evaluation "
        "seeds and the live Yahoo benchmark are unpinned, and the exact 100-epoch "
        "DeepSeek 10% CPPO training lineage is absent.",
    ),
    "SYS-GURU-AGENTS": (
        "Y",
        "A pinned v1 paper audit executes the paper-era notebook and reproduces all "
        "7 shipped workbook paths, but only 2/70 Table 1 cells (the two benchmark "
        "MDDs), 0/7 complete rows, 0/42 figure units, and 0/5 verbatim prompts receive "
        "paper-result credit. The 35 archived GPT runs retain their tool logs, but "
        "the stated transaction cost is not applied, agent and benchmark frequencies "
        "differ, QQQ/SPY stand in for indices, point-in-time filings are absent, the "
        "claimed deterministic scorer is LLM-mediated, and no raw run satisfies the "
        "strict output contract. Coverage is U.S.-only and not the six-country "
        "common-task panel.",
    ),
    "SYS-MASS": (
        "N",
        "A pinned paper audit verifies a 242-day 2023 SSE50-like base/label panel and "
        "safely decodes a 263-date, 16-type learned distribution trajectory. This is "
        "native optimizer state, not a signal or return: all 277 numeric cells in "
        "Tables 1--4 remain unverifiable because decisions, other stock pools, "
        "baselines, backtests, and cost logs are not shipped.",
    ),
    "SYS-QUANT-AGENT-HFT": (
        "N",
        "A pinned arXiv-v4 audit checks all 272 numeric cells in Tables 1--2 and "
        "all 1,600 released benchmark CSVs. Every asset/horizon set has 100x100 "
        "rows and exact paper date endpoints, but the original 5,000-bar panels "
        "are absent. The paper-described recent-40-close LR reconstruction matches "
        "0/8 accuracies; all eight match only with an undocumented three-bar feature "
        "gap. No experiment evaluator, native predictions/risk ratios, baseline "
        "implementations, seeds/splits, portfolio paths, or numeric 1-hour paths "
        "are shipped, so zero paper result cells count as native reproductions.",
    ),
    "SYS-TRADING-AGENTS": (
        "N",
        "A pinned arXiv-v7 audit enumerates all 77 numeric cells in Table 1: 68 "
        "direct results and 9 derived improvements, plus 12 quantitative result "
        "claims in prose/figures. The nearest official source is v0.1.0, released "
        "about 52 hours after the paper; its parent contains only three site files. "
        "All 39 Python files compile and dependency-isolated native graph routing "
        "executes deterministically, while 14/45 paper mechanism dimensions match "
        "or have meaningful analogues. These are architecture components, not the "
        "paper experiment. No frozen multimodal data, exact config, backtest, "
        "portfolio/execution path, baselines, metrics, actions, fills, NAVs, returns, "
        "traces, seeds, or costs are shipped, so 0/77 table cells count as native "
        "reproductions. The paper itself has unresolved CR/AR formula, improvement, "
        "MDD-bound, and asset-universe inconsistencies.",
    ),
    "SYS-TRADING-R1": (
        "N",
        "A pinned arXiv-v1 audit confirms the official repository still contains "
        "only one 49-byte release-soon README and no code, model, dataset, config, "
        "prediction, trade, or return artifact. Literal reconstructions of Algorithm "
        "S1 and the decision matrix receive paper-specification credit only: 0/312 "
        "table cells and 0/36 Figure 5 annotations are natively reproduced. The paper "
        "also conflicts on the NVDA Trading-R1 Sharpe (2.72 table versus 1.881 figure "
        "and 1.88 prose), forward versus trailing labels, decision-matrix asymmetry, "
        "and the official project page's released claim versus the placeholder repo.",
    ),
}


# Paper-level audits can establish a precise evidence boundary even when the
# authors released no system artifact. Keep that evidence distinct from the
# static artifact notes above so baseline/source-adjacent material is not
# mistaken for native implementation evidence.
PAPER_ONLY_AUDIT_NOTES = {
    "SYS-ALPHA-AGENTS": (
        "A pinned arXiv-v1 AlphaAgents audit rebuilds the official nine-page TeX "
        "source at 99.77% extracted-token multiset Jaccard and recovers seven "
        "commented-out portfolio definitions containing 77 ticker memberships. "
        "These are document and source-specification evidence, not native agent "
        "outputs: 0/20 plotted performance series reproduce. No author-linked "
        "implementation, Bloomberg/filing/price snapshot, immutable GPT-4o request, "
        "filled risk-profile prompt, agent decision, debate trace, Phoenix score, "
        "raw return path, or plot array is released. Five unaffiliated GitHub "
        "reimplementations materially change the model, framework, data, universe, "
        "dates, or benchmark and receive no native credit. The two local M0 factor "
        "scores, monthly deciles, long-short weights, and return streams are "
        "researcher-supplied narrative translations and receive no AlphaAgents-result "
        "credit."
    ),
    "SYS-ALPHA-GPT": (
        "A pinned Alpha-GPT lineage audit rebuilds the official arXiv-v1, "
        "arXiv-v2, and Alpha-GPT 2.0 TeX sources and separately checks the "
        "authoritative EMNLP 2025 final. These are document and specification "
        "findings, not native system outputs: Alpha-GPT v1 reproduces 0/20 "
        "displayed numeric cells and 0/3 backtest line series; the v2/ACL-final "
        "study reproduces 0/47 displayed numeric cells and 0/2 search-enhancement "
        "line series. Alpha-GPT 2.0 is explicitly a work-in-progress architecture "
        "draft with no experiment or empirical result denominator. Three of four "
        "published formula examples execute only under a declared conventional "
        "operator stub; the showcased Flow of Funds expression gives div one "
        "argument and cwise_mul three despite the paper's validation premise. No "
        "author-linked code, data snapshot, universe membership, full prompts, "
        "model requests, memory, generated alpha set, GP state, portfolio evaluator, "
        "seeds, raw arrays, or result export is released. Ten complete repository "
        "searches find only unaffiliated paper-inspired code that omits the native "
        "search, evaluator, data, and results. Both local M0 factor scores remain "
        "researcher-supplied narrative translations and receive no Alpha-GPT-result "
        "credit."
    ),
    "SYS-ALPHA-JUNGLE": (
        "A pinned three-edition Alpha-Jungle audit inventories 64 official AAAI "
        "table cells, 956 original-v1 cells, and 1,312 current-v3 extended-table "
        "cells. Zero official result cells reproduce, and no author-linked source, "
        "factor pools, search traces, exact inputs, seeds, or result records are "
        "released. Three of six disclosed factor formulas execute only as monthly "
        "JKP U.S. adaptations; these are formula components, not the paper experiment, "
        "and receive no paper-result credit. An unaffiliated community repository "
        "fails package import and all three test collections and conflicts with core "
        "paper settings, so it receives no native credit. Of 932 v1/v3 common result "
        "cells, 925 are identical at display precision; 16 ablation values persist "
        "through an AR-to-AER metric-definition change without released lineage, and "
        "the v3 appendix still labels 228 result cells AR."
    ),
    "SYS-EFS": (
        "A pinned two-version EFS audit inventories 773 original-v1 and 877 "
        "current-v2 numeric table-result cells. Executing the cited 1/N formula "
        "on the exact 623-row matrices in the official ASMCVaR release reproduces "
        "5/773 v1 cells and 8/877 v2 cells at each paper's display precision; all "
        "are cited-baseline evidence and zero are native EFS results. No author-linked "
        "EFS source, exact configuration, model snapshot, data snapshot, factor pool, "
        "search trace, actions, weights, returns, seeds, or result records are released. "
        "All 240 v2 benchmark cells common to v1 are rounded carryovers, including "
        "48 values relabelled from v1 asset Scores-to-Weights to the materially "
        "different v2 RMT/QP factor-weighting mechanism without released run lineage."
    ),
    "SYS-FAMA": (
        "A pinned ACL-final FAMA audit inventories all 65 numeric performance cells "
        "in Tables 1, 2, and 4 and all 38 visible result markers in Figures 3--4; "
        "zero are reproduced. The official record links only the PDF, and no "
        "author-linked code, data snapshot, immutable model/API request, filled "
        "prompt, final mined factors, search/experience traces, predictions, "
        "portfolio paths, seeds, or raw results are released. Appendix D supplies "
        "one prompt template but leaves function_definition unresolved. Exact "
        "reconstruction is also blocked by paper conflicts: 38 claimed initial "
        "factors versus 71 Appendix-B identifiers, a printed correlation equation "
        "without the Pearson square root, Algorithm 1 adding every generated factor "
        "outside its improvement conditional, and a fitting window that crosses the "
        "declared training/validation split. The local M1 mapping preserves only a "
        "momentum/trend motif; its other characteristics and portfolio rule are "
        "researcher supplied and receive no FAMA-result credit."
    ),
    "SYS-FIN-VISION": (
        "A pinned FinVision audit validates the official nine-page paper, the "
        "complete 22-file arXiv manuscript bundle, five printed prompt templates, "
        "and the author's 133-page thesis. The thesis repeats all 72 displayed "
        "performance cells, and the nine FinAgent cells trace to FinAgent Appendix "
        "Table 7, but these are corroboration and transcription rather than native "
        "execution: 0/72 cells reproduce. The arXiv archive contains no FinVision "
        "system code, environment, configuration, or data pipeline, and no original "
        "news/price snapshot, runtime LLM request/response, action, fill, reward, "
        "cash, or equity path is released. A pinned current-Yahoo diagnostic matches "
        "3/9 Market cells at display precision but receives zero result credit because "
        "the original price field/snapshot and metric conventions are unspecified. "
        "The paper's 42/145 trading-day counts also differ from the 41/147 literal "
        "sessions over its printed dates without a stated transformation. Public "
        "author/index/archive searches recovered no attributable implementation; "
        "this bounded negative result is not proof that private or deleted artifacts "
        "never existed."
    ),
    "SYS-QUANT-AGENT-SELF-IMPROVING": (
        "A pinned arXiv-v1 QuantAgent audit rebuilds the official 15-page TeX "
        "source at 99.93% extracted-token multiset Jaccard and audits all four "
        "published Python listings. Only the VolatilityBreakout formula executes, "
        "and only after stubbing the unreleased idea_factor.Factor base; both "
        "mentor-rejected Three Soldiers versions raise on ordinary aligned data, "
        "while the printed mentor-passed V3 has a SyntaxError. These are document "
        "and conditional component findings, not native agent outputs: 0/17 plotted "
        "line series and 0/400 heatmap cells reproduce. No author-linked pipeline, "
        "idea-factor framework, 500-stock membership, 2023 market snapshot, prompts, "
        "knowledge base, generated signal library, model fit, raw result arrays, "
        "seeds, or runtime lock is released. The two local M0 mappings and separate "
        "C-conditional monthly ATR14 adaptation receive no QuantAgent-result credit."
    ),
    "SYS-FLAG-TRADER": (
        "A pinned ACL-final/arXiv-v3 audit inventories all 360 displayed numeric "
        "result cells. Six of 20 checked Buy-and-Hold baseline cells reproduce "
        "literally from the first author-linked InvestorBench release, but zero "
        "FLAG-Trader cells reproduce. The 22 paper settings, prompt template, and "
        "TeX are static document evidence. No author-linked FLAG-Trader source, "
        "checkpoint, exact configuration, seeds, actions, equity paths, or result "
        "records are released. State, transaction-cost, reward initialization, "
        "BTC annualization, KL-loss, value-clipping, and test-selection details "
        "are missing or internally conflicting."
    ),
    "SYS-LLM-FACTOR": (
        "A pinned arXiv-v1/ACL-final LLMFactor audit inventories all 206 displayed "
        "experimental cells: 82 native LLMFactor and 124 baseline cells. The official "
        "nine-file TeX archive rebuilds unpatched to 12 pages but contains no system "
        "code or raw result. Three English prompt skeletons and the ACC/MCC formulas "
        "execute only as declared deterministic component fixtures; no LLM request or "
        "paper response is replayed. Thus 0/82 native and 0/206 total cells reproduce. "
        "No author-linked implementation, exact data snapshot, split, preprocessing, "
        "universe, stock matcher, API request log, response parser, seed, prediction, "
        "confusion matrix, or raw array is released. Six complete GitHub searches find "
        "only two 2025 unaffiliated implementations that change models, prompts, data, "
        "or windows and reproduce no paper cell. Four Table-3 averages cannot be "
        "recovered by rounding the displayed Table-2 inputs; the EDT-accuracy "
        "superiority prose and appendix template-winner prose are also overbroad. The "
        "local M0 monthly characteristic portfolio has no text, SKGP, daily labels, "
        "or paper metrics and receives no LLMFactor-result credit."
    ),
}


TARGETED_EXECUTION = {
    "SYS-ALPHA-AGENT": "paper_audit:completed_zero_of_100_native_results_post_paper_rewrite",
    "SYS-ALPHA-AGENTS": "paper_audit:completed_source_document_and_7_portfolios_zero_of_20_plotted_series_no_native_agent_pipeline",
    "SYS-ALPHA-GPT": "paper_audit:completed_v1_zero_of_20_numeric_cells_zero_of_3_lines_final_zero_of_47_numeric_cells_zero_of_2_lines_alpha_gpt2_no_empirical_results",
    "SYS-ALPHA-JUNGLE": "paper_audit:completed_zero_of_64_published_cells_zero_native_results_three_of_six_formula_trees_conditionally_adapted",
    "SYS-ALPHA-MEMO": "paper_audit:completed_zero_of_474_native_results",
    "SYS-ALPHA-R1": "paper_audit:completed_zero_of_652_native_results_official_placeholder",
    "SYS-ALPHA-QUANTER": "paper_audit:completed_one_of_790_current_snapshot_buy_hold_match",
    "SYS-AUTOMATE-STRATEGY": "paper_audit:completed_zero_of_40_integrated_portfolio_cells_factor_component_only",
    "SYS-CONTEST-TRADE": "paper_audit:completed_zero_of_49_native_results",
    "SYS-CRYPTO-TRADE": "paper_audit:partial_174_of_468_traditional_baseline_cells",
    "SYS-EFS": "paper_audit:completed_5_of_773_cited_baseline_cells_zero_efs_native_results_v2_revision_audited",
    "SYS-FAMA": "paper_audit:completed_zero_of_65_table_results_zero_of_38_figure_markers_no_native_pipeline_equation_conflicts",
    "SYS-FIN-CON": "paper_audit:completed_zero_of_306_native_results_official_code_not_released",
    "SYS-FIN-AGENT": "paper_audit:completed_zero_of_1061_published_result_units_substantial_source_conflicts",
    "SYS-EMPIRICAL-ASSET-PRICING-LLM": "paper_audit:completed_zero_of_162_v2_table_results_missing_hybrid_pipeline_and_v2_lineage",
    "SYS-FLAG-TRADER": "paper_audit:completed_6_of_360_author_linked_buy_hold_baseline_cells_zero_flag_native_results",
    "SYS-FIN-MEM": "paper_audit:completed_16_of_235_current_snapshot_buy_hold_matches",
    "SYS-FIN-VISION": "paper_audit:completed_zero_of_72_performance_cells_no_public_system_source",
    "SYS-HEDGE-AGENTS": "paper_audit:completed_zero_of_236_numeric_cells_static_site_not_system_source",
    "SYS-FIN-RL-DEEPSEEK": "paper_audit:completed_zero_of_36_native_results_released_checkpoints_mismatch",
    "SYS-GURU-AGENTS": "paper_audit:completed_two_of_70_native_table_cells_source_workbook_only",
    "SYS-GPT-SIGNAL": "paper_audit:partial_1549_of_1554_published_units_author_thesis_source_recovery",
    "SYS-LLM-FACTOR": "paper_audit:completed_prompt_metric_components_zero_of_82_native_cells_zero_of_206_total_cells_no_author_code",
    "SYS-MASS": "paper_audit:completed_zero_of_277_native_results_internal_state_only",
    "SYS-QUANT-AGENT-HFT": "paper_audit:completed_zero_of_272_native_results_undocumented_feature_gap",
    "SYS-QUANT-AGENT-SELF-IMPROVING": "paper_audit:completed_document_and_4_listings_zero_of_17_line_series_zero_of_400_heatmap_cells_no_native_agent_pipeline",
    "SYS-QUANT-EVOLVER": "paper_audit:completed_zero_of_75_native_results_component_gate_separate",
    "SYS-QUANTA-ALPHA": "paper_audit:completed_zero_of_344_native_table_results_components_only",
    "SYS-RAPTOR": "paper_audit:completed_16_of_42_author_output_scalar_units_zero_end_to_end_result_cells",
    "SYS-RD-AGENT-QUANT": "paper_audit:completed_zero_of_534_native_results_components_only",
    "SYS-TRADING-AGENTS": "paper_audit:completed_zero_of_77_native_results",
    "SYS-TRADING-R1": "paper_audit:completed_zero_of_348_published_numeric_units_official_placeholder",
}


OUTPUT_BLOCKS = {
    "SYS-AUTOMATE-STRATEGY": "A3_output_lacks_six_country_security_mapping",
    "SYS-CRYPTO-TRADE": "A3_wrong_asset_class_crypto",
    "SYS-GURU-AGENTS": "A3_US_only_not_six_country",
    "SYS-GPT-SIGNAL": "A3_US_only_not_six_country",
    "SYS-RAPTOR": "A3_US_only_not_six_country",
}


# The frozen static artifact audit used an over-broad "coming soon" heuristic:
# QuantaAlpha's roadmap for a separate future project demoted an otherwise
# complete code+environment+runner+config package to R1. The paper-level audit
# executes native components and justifies the corrected static package tier.
STATIC_TIER_OVERRIDES = {
    "SYS-QUANTA-ALPHA": "R3",
}


FIELDS = [
    "system_id",
    "native_task",
    "public_artifact_status",
    "static_tier",
    "native_dated_signal_or_return_shipped",
    "prespecified_G7_monthly_common_task_compatible",
    "blocking_stage",
    "evidence_url",
    "concise_evidence_note",
    "targeted_execution_audit_status",
    "fidelity_class",
]


def first_url(value: str) -> str:
    matches = URL_RE.findall(value or "")
    return matches[0] if matches else ""


def native_task(row: dict[str, str]) -> str:
    text = row["inclusion_exclusion_rationale"].strip()
    text = re.sub(r"^IN:\s*", "", text)
    return text.rstrip(".")


def main() -> None:
    with CENSUS.open(encoding="utf-8", newline="") as stream:
        census = list(csv.DictReader(stream, delimiter="|"))
    with AUDIT.open(encoding="utf-8", newline="") as stream:
        audit_rows = list(csv.DictReader(stream))
    audit = {row["system_id"]: row for row in audit_rows}

    ft = [row for row in census if row["stratum"] in {"F", "T"}]
    if len(ft) != EXPECTED_FT or len({row["system_id"] for row in ft}) != EXPECTED_FT:
        raise ValueError("frozen census must contain 67 unique F/T systems")
    if any(row["system_id"] not in audit for row in ft):
        raise ValueError("artifact audit does not cover every F/T system")

    output_rows = []
    for source in ft:
        sid = source["system_id"]
        observed = audit[sid]
        listed = observed["public_artifact_listed"] == "Y"
        reachability = observed["reachability_outcome"]

        if not listed:
            artifact_status = "not_listed"
            shipped = "N"
            block = "A0_no_public_artifact"
            fidelity = "F0_no_public_artifact"
            evidence = first_url(source["primary_record"])
            note = PAPER_ONLY_AUDIT_NOTES.get(
                sid,
                (
                    f"The frozen primary record identifies {native_task(source)}; "
                    "the registry lists no public artifact, so no native dated output "
                    "was available for static inspection."
                ),
            )
        elif reachability == "check_failed":
            artifact_status = "listed_check_failed"
            shipped = "uncertain"
            block = "A1_artifact_access_unresolved"
            fidelity = "F0_artifact_unresolved"
            evidence = first_url(observed["artifact_urls"])
            note = (
                "The listed anonymous artifact returned HTTP 401 during the frozen "
                "audit; its package and any native outputs could not be resolved."
            )
        elif reachability == "unreachable_all":
            artifact_status = "listed_unreachable"
            shipped = "uncertain"
            block = "A1_artifact_access_unresolved"
            fidelity = "F0_artifact_unresolved"
            evidence = first_url(observed["artifact_urls"])
            note = (
                "The listed project page returned HTTP 404 during the frozen audit; "
                "its package and any native outputs could not be resolved."
            )
        else:
            artifact_status = "reachable_static_snapshot"
            evidence = first_url(observed["artifact_urls"])
            try:
                shipped, note = ARTIFACT_NOTES[sid]
            except KeyError as exc:
                raise ValueError(f"missing static artifact note for {sid}") from exc
            if shipped == "Y":
                block = OUTPUT_BLOCKS[sid]
                fidelity = "F2_dated_output_task_incompatible"
            else:
                block = "A2_no_shipped_native_dated_output"
                fidelity = "F1_static_no_native_output"

        output_rows.append(
            {
                "system_id": sid,
                "native_task": native_task(source),
                "public_artifact_status": artifact_status,
                "static_tier": STATIC_TIER_OVERRIDES.get(
                    sid, observed["static_fidelity_tier"]
                ),
                "native_dated_signal_or_return_shipped": shipped,
                "prespecified_G7_monthly_common_task_compatible": "N",
                "blocking_stage": block,
                "evidence_url": evidence,
                "concise_evidence_note": note,
                "targeted_execution_audit_status": TARGETED_EXECUTION.get(
                    sid, "not_targeted_in_legacy_execution_audit"
                ),
                "fidelity_class": fidelity,
            }
        )

    if len({row["system_id"] for row in output_rows}) != EXPECTED_FT:
        raise ValueError("output ledger does not contain 67 unique systems")
    if any(row["prespecified_G7_monthly_common_task_compatible"] != "N" for row in output_rows):
        raise ValueError("strict compatibility crosswalk unexpectedly contains a compatible row")

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    temporary = OUTPUT.with_suffix(".csv.tmp")
    with temporary.open("w", encoding="utf-8", newline="") as stream:
        writer = csv.DictWriter(
            stream, fieldnames=FIELDS, lineterminator="\n"
        )
        writer.writeheader()
        writer.writerows(output_rows)
    temporary.replace(OUTPUT)


if __name__ == "__main__":
    main()
