#!/usr/bin/env python3
"""Build the complete screened-corpus bibliography and manuscript citation macros."""
from __future__ import annotations

import argparse
import csv
from pathlib import Path
import re
from typing import Iterable


ROOT = Path(__file__).resolve().parents[1]
PROHIBITED = ("López de Prado", "Lopez de Prado", "LopezDePrado")


def read_csv(path: Path, delimiter: str = ",") -> list[dict[str, str]]:
    with path.open(newline="", encoding="utf-8-sig") as stream:
        return list(csv.DictReader(stream, delimiter=delimiter))


def require(condition: bool, message: str) -> None:
    if not condition:
        raise AssertionError(message)


def normalized_urls(registry: Iterable[dict[str, str]]) -> set[str]:
    return {
        url.strip()
        for row in registry
        for url in row["primary_record"].split(" ; ")
        if url.strip()
    }


def latex_text(value: str) -> str:
    value = re.sub(r"\s*\([^)]*[^\x00-\x7f][^)]*\)", "", value)
    replacements = {
        "‑": "-", "–": "--", "—": "---", "“": "``", "”": "''", "’": "'",
        "ü": r"{\"u}", "&": r"\&", "%": r"\%", "#": r"\#", "_": r"\_",
    }
    return "".join(replacements.get(char, char) for char in value)


def bibtex_entry(row: dict[str, str]) -> str:
    authors = " and ".join(latex_text(author.strip()) for author in row["authors"].split(";") if author.strip())
    lines = [f"@{row['entry_type']}{{{row['bibtex_key']},", f"  author = {{{authors}}},",
             f"  title = {{{{{latex_text(row['title'])}}}}},", f"  year = {{{row['year']}}},"]
    if row["entry_type"] == "inproceedings":
        lines.append(f"  booktitle = {{{latex_text(row['venue'])}}},")
    elif row["entry_type"] == "article":
        lines.append(f"  journal = {{{latex_text(row['venue'])}}},")
    elif row["venue"] == "arXiv":
        lines.extend([
            f"  eprint = {{{row['source_identifier']}}},",
            "  archivePrefix = {arXiv},",
        ])
        if row["primary_class"]:
            lines.append(f"  primaryClass = {{{row['primary_class']}}},")
    if "doi.org/" in row["primary_url"]:
        lines.append(f"  doi = {{{row['primary_url'].split('doi.org/', 1)[1]}}},")
    lines.append(f"  url = {{{row['primary_url']}}}")
    lines.append("}")
    return "\n".join(lines)


def citation_macro(name: str, keys: list[str]) -> str:
    return f"\\newcommand{{\\{name}}}{{\\cite{{{','.join(sorted(keys))}}}}}"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, default=ROOT)
    args = parser.parse_args()
    root = args.root.resolve()
    registry = read_csv(root / "literature_review/census_v1/system_registry.csv", delimiter="|")
    metadata = read_csv(root / "literature_review/census_v1/primary_record_metadata.csv")

    require(len(registry) == 103, "pre-trim lineage count changed")
    require(sum(row["main_FT"] == "Y" for row in registry) == 67, "retained F/T lineage count changed")
    require(len(metadata) == 104, "primary-record link count changed")
    require({row["primary_url"] for row in metadata} == normalized_urls(registry),
            "metadata URLs do not exactly cover the screened registry")
    require(len({row["canonical_work_id"] for row in metadata}) == 98,
            "canonical pre-trim work count changed")
    require(sum(row["main_ft"] == "yes" for row in metadata) == 71,
            "retained primary-record link count changed")
    require(len({row["canonical_work_id"] for row in metadata if row["main_ft"] == "yes"}) == 69,
            "retained canonical work count changed")
    require(len({row["bibtex_key"] for row in metadata}) == len(metadata), "duplicate BibTeX key")
    for field in ("title", "authors", "year", "venue", "metadata_source"):
        require(all(row[field].strip() for row in metadata), f"missing metadata field: {field}")
    for work_id in {row["canonical_work_id"] for row in metadata}:
        preferred = [row for row in metadata if row["canonical_work_id"] == work_id
                     and row["preferred_citation"] == "yes"]
        require(len(preferred) == 1, f"canonical work must have exactly one preferred record: {work_id}")
    joined = "\n".join("|".join(row.values()) for row in metadata)
    require(not any(name.casefold() in joined.casefold() for name in PROHIBITED),
            "prohibited author appears in corpus metadata")

    preferred = sorted((row for row in metadata if row["preferred_citation"] == "yes"),
                       key=lambda row: (row["authors"].split(";")[0], row["year"], row["title"]))
    bibliography = "% Generated by scripts/build_census_citation_assets.py; do not edit by hand.\n\n"
    bibliography += "\n\n".join(bibtex_entry(row) for row in preferred) + "\n"
    (root / "docs/paper/census_primary_records.bib").write_text(bibliography, encoding="utf-8")

    retained = [row for row in preferred if row["main_ft"] == "yes"]
    formula_rows = [row for row in retained if "F" in row["strata"].split("; ")]
    trading_rows = [row for row in retained if "T" in row["strata"].split("; ")]
    formula_keys = [row["bibtex_key"] for row in formula_rows]
    trading_keys = [row["bibtex_key"] for row in trading_rows]
    require(len(formula_keys) + len(trading_keys) == 69, "retained works are not partitioned into F/T")
    macro_lines = [
        "% Generated by scripts/build_census_citation_assets.py; do not edit by hand.",
        r"\newcommand{\PretrimLineageCount}{103\xspace}",
        r"\newcommand{\PretrimWorkCount}{98\xspace}",
        r"\newcommand{\RetainedLineageCount}{67\xspace}",
        r"\newcommand{\RetainedWorkCount}{69\xspace}",
        citation_macro("FormulaCorpusCitationsThroughTwentyFive",
                       [row["bibtex_key"] for row in formula_rows if int(row["year"]) <= 2025]),
        citation_macro("FormulaCorpusCitationsTwentySix",
                       [row["bibtex_key"] for row in formula_rows if int(row["year"]) == 2026]),
        citation_macro("TradingCorpusCitationsThroughTwentyFour",
                       [row["bibtex_key"] for row in trading_rows if int(row["year"]) <= 2024]),
        citation_macro("TradingCorpusCitationsTwentyFive",
                       [row["bibtex_key"] for row in trading_rows if int(row["year"]) == 2025]),
        citation_macro("TradingCorpusCitationsTwentySix",
                       [row["bibtex_key"] for row in trading_rows if int(row["year"]) == 2026]),
        "",
    ]
    (root / "docs/paper/generated_corpus_citations.tex").write_text("\n".join(macro_lines), encoding="utf-8")

    output = root / "paper_runs/submission_evidence/replication_scope/pretrim_primary_record_inventory.csv"
    output.parent.mkdir(parents=True, exist_ok=True)
    with output.open("w", newline="", encoding="utf-8") as stream:
        writer = csv.DictWriter(stream, fieldnames=metadata[0].keys())
        writer.writeheader()
        writer.writerows(metadata)

    sections = [
        ("Retained formula-discovery works", [row for row in retained if "F" in row["strata"].split("; ")]),
        ("Retained trading works", [row for row in retained if "T" in row["strata"].split("; ")]),
        ("Screened-out benchmark, comparator, and adjacent works", [row for row in preferred if row["main_ft"] == "no"]),
    ]
    markdown = [
        "# Complete pre-trim source bibliography",
        "",
        "The screened universe contains **103 system lineages** represented by 105 registry links,",
        "104 distinct URLs, and **98 canonical scholarly works** after duplicate publication",
        "manifestations are collapsed. The retained formula/trading sample contains **67 lineages**",
        "and **69 canonical works**. Every retained work is cited in the ICAIF manuscript.",
        "",
    ]
    for heading, group in sections:
        markdown.extend([f"## {heading} ({len(group)})", ""])
        for row in group:
            author = row["authors"].split(";")[0]
            if ";" in row["authors"]:
                author += " et al."
            markdown.append(
                f"- **{author} ({row['year']}). {row['title']}.** "
                f"Systems: {row['system_names']}. [{row['metadata_source']}]({row['primary_url']}) "
                f"(`{row['bibtex_key']}`)."
            )
        markdown.append("")
    (root / "docs/full_corpus_bibliography.md").write_text("\n".join(markdown), encoding="utf-8")

    print({
        "screened_lineages": len(registry),
        "screened_record_links": sum(len([u for u in row["primary_record"].split(" ; ") if u.strip()]) for row in registry),
        "screened_distinct_urls": len(metadata),
        "screened_canonical_works": len(preferred),
        "retained_lineages": sum(row["main_FT"] == "Y" for row in registry),
        "retained_canonical_works": len(retained),
        "formula_works": len(formula_keys),
        "trading_works": len(trading_keys),
    })
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
