#!/usr/bin/env python3
"""Build the frozen native-fidelity ledger for the main F/T census.

This is a static evidence crosswalk.  It does not install, import, or execute
third-party artifacts.  A system is common-task compatible only if the public
materials ship native dated outputs with timing and identifiers sufficient for
the prespecified six-country monthly JKP evaluator without replacing the
system's core mechanism.
"""
from __future__ import annotations

import csv
from pathlib import Path
import re


ROOT = Path(__file__).resolve().parents[1]
CENSUS = ROOT / "literature_review" / "census_v1" / "system_registry.csv"
AUDIT = (
    ROOT
    / "paper_runs"
    / "submission_evidence"
    / "artifact_audit"
    / "artifact_audit.csv"
)
OUTPUT = (
    ROOT
    / "paper_runs"
    / "submission_evidence"
    / "native_fidelity_ledger.csv"
)
EXPECTED_FT = 67
URL_RE = re.compile(r"https?://[^;\s]+")


# Static observations are pinned to the immutable heads recorded in the
# artifact audit.  "Output" below means an output generated by the named
# system, not raw inputs, prompts, labels, factor expressions, or example
# configuration.
ARTIFACT_NOTES = {
    "SYS-ALPHA-AGENT": (
        "N",
        "The snapshot ships China-A-share research code and DSL expressions; "
        "its README says the panel and large binaries are not in Git, and no "
        "dated native signal or return series is bundled.",
    ),
    "SYS-ALPHA-MEMO": (
        "N",
        "A pinned arXiv-v1 audit enumerates all 484 numeric experimental cells in "
        "Tables 2--9: 474 results and 10 configuration cells. The official test and "
        "a deterministic native synthetic smoke run pass, and the native parser can "
        "execute all five published formulas on synthetic arrays. These are components, "
        "not paper outputs. No Qlib data snapshot, search trajectory, factor pool, "
        "prediction, return, or table output is shipped, so 0/474 result cells count as "
        "native reproductions. The active runner's ICIR threshold is 0.02 versus the "
        "paper's 0.10, and source motif/context/gating behavior differs from the paper.",
    ),
    "SYS-ALPHA-R1": (
        "N",
        "The reachable repository contains one non-runnable/pseudocode file "
        "and no dated native output.",
    ),
    "SYS-AUTOMATE-STRATEGY": (
        "Y",
        "The snapshot bundles seven 2022Q4 individual-factor analysis workbooks "
        "with IC summaries and quantile-return/turnover series, plus prompt logs. "
        "It does not ship the integrated 2023 portfolio path behind paper Table 4, "
        "and the factor outputs are not a six-country security-level signal panel.",
    ),
    "SYS-QUANTA-ALPHA": (
        "N",
        "The repository is explicitly described as non-runnable/pseudocode in "
        "the static audit; no dated native output is bundled.",
    ),
    "SYS-QUANT-EVOLVER": (
        "N",
        "The README states that the public repository is reusable framework code "
        "only and excludes private market data, experiment logs, and paper-specific "
        "reproduction scripts; example seeds are formulas, not dated outputs.",
    ),
    "SYS-RD-AGENT-QUANT": (
        "N",
        "The snapshot provides the broad R&D-Agent framework and quant runners, "
        "but no bundled dated output from the R&D-Agent-Quant lineage.",
    ),
    "SYS-ALPHA-QUANTER": (
        "N",
        "A pinned paper audit checks all 790 numeric cells in Tables 5--8 and "
        "10--14. The release ships 2,615 training/validation prompt-label rows: "
        "a current Yahoo retrieval reproduces 523 labels exactly and 2,612 reward "
        "regimes. A released-semantics market-baseline reconstruction matches 1/34 "
        "repeated Buy-and-Hold cells at display precision. These are components, "
        "not agent outputs; all 756 non-market cells lack checkpoints, actions, "
        "three-seed paths, logs, or human ratings, and the paper test split is absent.",
    ),
    "SYS-CONTEST-TRADE": (
        "N",
        "A pinned arXiv-v4 audit enumerates all 49 numeric cells in Tables 1--3. "
        "The released CLI runs a three-node agent graph that never calls either "
        "paper contest and does not construct the Sharpe-weighted portfolio. The "
        "isolated Research Contest lacks both required models and a method it calls; "
        "the isolated Data Contest ships two fixed models without rolling-training "
        "provenance, uses top-3 sorting rather than facility-location allocation, and "
        "changes the paper's signed ZI sum into a clipped positive-only average. No "
        "native inputs, outputs, evaluator, baselines, ablations, or seeds are shipped, "
        "so zero paper result cells count as native reproductions.",
    ),
    "SYS-CRYPTO-TRADE": (
        "Y",
        "The README ships a dated one-step ETH action/ROI example. A pinned paper-level "
        "audit additionally recomputes 174/180 displayed deterministic traditional-baseline "
        "cells (43/45 complete rows) from the native crypto data and environment, but no "
        "full-period LLM or time-series result paths are shipped. The evidence remains "
        "crypto rather than six-country equity output.",
    ),
    "SYS-FIN-CON": (
        "N",
        "The reachable repository contains a single statically insufficient file "
        "and no dated native output.",
    ),
    "SYS-FIN-MEM": (
        "N",
        "A pinned paper audit recomputes 16/40 repeated Buy-and-Hold metric cells "
        "from the released formula and a current Yahoo snapshot, including both full "
        "TSLA ablation rows. All 195 non-Buy-and-Hold cells remain unverifiable: the "
        "release ships fake/sample inputs but no native action paths, checkpoints, or "
        "five-trial outputs, and its sole config differs from the paper.",
    ),
    "SYS-FIN-RL-DEEPSEEK": (
        "N",
        "The snapshot ships training/backtest code and points to external Nasdaq "
        "datasets; its README gives aggregate result descriptions but no dated "
        "native signal or return series.",
    ),
    "SYS-GURU-AGENTS": (
        "Y",
        "The snapshot bundles dated quarterly Nasdaq-100 portfolio CSVs, analysis "
        "logs, and backtest workbooks.  Coverage is U.S.-only and not the six-country "
        "common-task panel.",
    ),
    "SYS-MASS": (
        "N",
        "A pinned paper audit verifies a 242-day 2023 SSE50-like base/label panel and "
        "safely decodes a 263-date, 16-type learned distribution trajectory. This is "
        "native optimizer state, not a signal or return: all 277 numeric cells in "
        "Tables 1--4 remain unverifiable because decisions, other stock pools, "
        "baselines, backtests, and cost logs are not shipped.",
    ),
    "SYS-QUANT-AGENT-HFT": (
        "N",
        "A pinned arXiv-v4 audit checks all 272 numeric cells in Tables 1--2 and "
        "all 1,600 released benchmark CSVs. Every asset/horizon set has 100x100 "
        "rows and exact paper date endpoints, but the original 5,000-bar panels "
        "are absent. The paper-described recent-40-close LR reconstruction matches "
        "0/8 accuracies; all eight match only with an undocumented three-bar feature "
        "gap. No experiment evaluator, native predictions/risk ratios, baseline "
        "implementations, seeds/splits, portfolio paths, or numeric 1-hour paths "
        "are shipped, so zero paper result cells count as native reproductions.",
    ),
    "SYS-TRADING-AGENTS": (
        "N",
        "The framework writes decisions and realized-return reflections to local "
        "runtime state, but the pinned snapshot bundles no dated native decision "
        "or return history.",
    ),
    "SYS-TRADING-R1": (
        "N",
        "The reachable repository is a one-file placeholder and contains no dated "
        "native output.",
    ),
}


TARGETED_EXECUTION = {
    "SYS-ALPHA-AGENT": "legacy_targeted:completed_no_direct_strategy_returns",
    "SYS-ALPHA-MEMO": "paper_audit:completed_zero_of_474_native_results",
    "SYS-CONTEST-TRADE": "paper_audit:completed_zero_of_49_native_results",
    "SYS-FIN-CON": "legacy_targeted:blocked_jkp_scope_incompatible",
    "SYS-GURU-AGENTS": "legacy_targeted:legacy_non_jkp_diagnostic_only",
    "SYS-QUANT-AGENT-HFT": "legacy_targeted:blocked_jkp_scope_incompatible",
    "SYS-QUANT-EVOLVER": "legacy_targeted:seed_idea_proxy_only_not_native_execution",
    "SYS-RD-AGENT-QUANT": "legacy_targeted:blocked_on_jkp_adapter",
    "SYS-TRADING-R1": "legacy_targeted:blocked_no_public_codebase",
}


OUTPUT_BLOCKS = {
    "SYS-AUTOMATE-STRATEGY": "A3_output_lacks_six_country_security_mapping",
    "SYS-CRYPTO-TRADE": "A3_wrong_asset_class_crypto",
    "SYS-GURU-AGENTS": "A3_US_only_not_six_country",
}


FIELDS = [
    "system_id",
    "native_task",
    "public_artifact_status",
    "static_tier",
    "native_dated_signal_or_return_shipped",
    "prespecified_G7_monthly_common_task_compatible",
    "blocking_stage",
    "evidence_url",
    "concise_evidence_note",
    "targeted_execution_audit_status",
    "fidelity_class",
]


def first_url(value: str) -> str:
    matches = URL_RE.findall(value or "")
    return matches[0] if matches else ""


def native_task(row: dict[str, str]) -> str:
    text = row["inclusion_exclusion_rationale"].strip()
    text = re.sub(r"^IN:\s*", "", text)
    return text.rstrip(".")


def main() -> None:
    with CENSUS.open(encoding="utf-8", newline="") as stream:
        census = list(csv.DictReader(stream, delimiter="|"))
    with AUDIT.open(encoding="utf-8", newline="") as stream:
        audit_rows = list(csv.DictReader(stream))
    audit = {row["system_id"]: row for row in audit_rows}

    ft = [row for row in census if row["stratum"] in {"F", "T"}]
    if len(ft) != EXPECTED_FT or len({row["system_id"] for row in ft}) != EXPECTED_FT:
        raise ValueError("frozen census must contain 67 unique F/T systems")
    if any(row["system_id"] not in audit for row in ft):
        raise ValueError("artifact audit does not cover every F/T system")

    output_rows = []
    for source in ft:
        sid = source["system_id"]
        observed = audit[sid]
        listed = observed["public_artifact_listed"] == "Y"
        reachability = observed["reachability_outcome"]

        if not listed:
            artifact_status = "not_listed"
            shipped = "N"
            block = "A0_no_public_artifact"
            fidelity = "F0_no_public_artifact"
            evidence = first_url(source["primary_record"])
            note = (
                f"The frozen primary record identifies {native_task(source)}; "
                "the registry lists no public artifact, so no native dated output "
                "was available for static inspection."
            )
        elif reachability == "check_failed":
            artifact_status = "listed_check_failed"
            shipped = "uncertain"
            block = "A1_artifact_access_unresolved"
            fidelity = "F0_artifact_unresolved"
            evidence = first_url(observed["artifact_urls"])
            note = (
                "The listed anonymous artifact returned HTTP 401 during the frozen "
                "audit; its package and any native outputs could not be resolved."
            )
        elif reachability == "unreachable_all":
            artifact_status = "listed_unreachable"
            shipped = "uncertain"
            block = "A1_artifact_access_unresolved"
            fidelity = "F0_artifact_unresolved"
            evidence = first_url(observed["artifact_urls"])
            note = (
                "The listed project page returned HTTP 404 during the frozen audit; "
                "its package and any native outputs could not be resolved."
            )
        else:
            artifact_status = "reachable_static_snapshot"
            evidence = first_url(observed["artifact_urls"])
            try:
                shipped, note = ARTIFACT_NOTES[sid]
            except KeyError as exc:
                raise ValueError(f"missing static artifact note for {sid}") from exc
            if shipped == "Y":
                block = OUTPUT_BLOCKS[sid]
                fidelity = "F2_dated_output_task_incompatible"
            else:
                block = "A2_no_shipped_native_dated_output"
                fidelity = "F1_static_no_native_output"

        output_rows.append(
            {
                "system_id": sid,
                "native_task": native_task(source),
                "public_artifact_status": artifact_status,
                "static_tier": observed["static_fidelity_tier"],
                "native_dated_signal_or_return_shipped": shipped,
                "prespecified_G7_monthly_common_task_compatible": "N",
                "blocking_stage": block,
                "evidence_url": evidence,
                "concise_evidence_note": note,
                "targeted_execution_audit_status": TARGETED_EXECUTION.get(
                    sid, "not_targeted_in_legacy_execution_audit"
                ),
                "fidelity_class": fidelity,
            }
        )

    if len({row["system_id"] for row in output_rows}) != EXPECTED_FT:
        raise ValueError("output ledger does not contain 67 unique systems")
    if any(row["prespecified_G7_monthly_common_task_compatible"] != "N" for row in output_rows):
        raise ValueError("strict compatibility crosswalk unexpectedly contains a compatible row")

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    temporary = OUTPUT.with_suffix(".csv.tmp")
    with temporary.open("w", encoding="utf-8", newline="") as stream:
        writer = csv.DictWriter(
            stream, fieldnames=FIELDS, lineterminator="\n"
        )
        writer.writeheader()
        writer.writerows(output_rows)
    temporary.replace(OUTPUT)


if __name__ == "__main__":
    main()
