#!/usr/bin/env python3
"""Build the frozen native-fidelity ledger for the main F/T census.

This is a static evidence crosswalk.  It does not install, import, or execute
third-party artifacts.  A system is common-task compatible only if the public
materials ship native dated outputs with timing and identifiers sufficient for
the prespecified six-country monthly JKP evaluator without replacing the
system's core mechanism.
"""
from __future__ import annotations

import csv
from pathlib import Path
import re


ROOT = Path(__file__).resolve().parents[1]
CENSUS = ROOT / "literature_review" / "census_v1" / "system_registry.csv"
AUDIT = (
    ROOT
    / "paper_runs"
    / "submission_evidence"
    / "artifact_audit"
    / "artifact_audit.csv"
)
OUTPUT = (
    ROOT
    / "paper_runs"
    / "submission_evidence"
    / "native_fidelity_ledger.csv"
)
EXPECTED_FT = 67
URL_RE = re.compile(r"https?://[^;\s]+")


# Static observations are pinned to the immutable heads recorded in the
# artifact audit.  "Output" below means an output generated by the named
# system, not raw inputs, prompts, labels, factor expressions, or example
# configuration.
ARTIFACT_NOTES = {
    "SYS-ALPHA-AGENT": (
        "N",
        "A pinned arXiv-v2 audit enumerates all 106 numeric cells in Tables 1--2: "
        "100 results and 6 trading-day configurations, plus 18 quantitative result "
        "claims in figures/text. The official Git history begins in July 2026, more "
        "than a year after the paper, and implements a different CSI1000/Tushare "
        "framework. Its 80 tests pass with import-only dependency stubs and four "
        "named base factors execute deterministically on synthetic data, but these "
        "are post-paper components. The source lacks the paper's three agents, AST "
        "subtree originality, regularizers, LightGBM/Qlib portfolio, baselines, "
        "prompts, trials, factors, and outputs. The linked 2026 data package has the "
        "wrong markets, source, and vintage, so 0/100 table result cells count as "
        "native reproductions.",
    ),
    "SYS-ALPHA-MEMO": (
        "N",
        "A pinned arXiv-v1 audit enumerates all 484 numeric experimental cells in "
        "Tables 2--9: 474 results and 10 configuration cells. The official test and "
        "a deterministic native synthetic smoke run pass, and the native parser can "
        "execute all five published formulas on synthetic arrays. These are components, "
        "not paper outputs. No Qlib data snapshot, search trajectory, factor pool, "
        "prediction, return, or table output is shipped, so 0/474 result cells count as "
        "native reproductions. The active runner's ICIR threshold is 0.02 versus the "
        "paper's 0.10, and source motif/context/gating behavior differs from the paper.",
    ),
    "SYS-ALPHA-R1": (
        "N",
        "A pinned arXiv-v1 audit enumerates all 652 displayed numeric result "
        "cells: 124 cells in Tables 1--3 and 528 cells in six heatmaps, plus "
        "27 quantitative result claims in prose. The paper says the full "
        "implementation and resources are available, but the only paper-era "
        "revision is a two-line title README and the current three-commit "
        "history still contains only one README marking inference code and "
        "model weights Coming Soon. No code, environment, prompts, checkpoint, "
        "market/news data, factor lists, betas, baselines, seeds, paths, or "
        "outputs are shipped, so 0/652 table/heatmap cells and 0/70 audited "
        "implementation dimensions count as native reproductions. The local "
        "M0 narrative motif proxy remains secondary and receives no paper-result "
        "or mechanism credit.",
    ),
    "SYS-AUTOMATE-STRATEGY": (
        "Y",
        "The snapshot bundles seven 2022Q4 individual-factor analysis workbooks "
        "with IC summaries and quantile-return/turnover series, plus prompt logs. "
        "It does not ship the integrated 2023 portfolio path behind paper Table 4, "
        "and the factor outputs are not a six-country security-level signal panel.",
    ),
    "SYS-QUANTA-ALPHA": (
        "N",
        "A pinned three-revision paper audit enumerates 344 numeric result table "
        "cells, 40 labeled figure/diagram values, 47 discrete unlabeled marker "
        "points, and 10 raster return curves. The official release is substantial: "
        "all 135 Python files in both the initial and current revisions compile, "
        "and dependency-isolated native AST, trajectory persistence, lineage, and "
        "crossover-selection components execute. These are architecture components, "
        "not paper results. The checked-in experiment and mining-loop configs conflict "
        "with the paper, claimed trajectory-segment repair/splicing is not structurally "
        "implemented, and the sole upstream test fails because its template is absent. "
        "No approximately-150-factor pool, trajectories, exact model/API runs, baselines, "
        "seeds, predictions, portfolios, returns, or plot arrays are shipped, so 0/344 "
        "table cells count as native reproductions. Large v1/v2-to-v3 result revisions "
        "lack released lineage, and v3 contains direct figure/prose inconsistencies.",
    ),
    "SYS-QUANT-EVOLVER": (
        "N",
        "A pinned arXiv-v1 audit enumerates all 75 numeric result cells in the two "
        "paper tables plus 31 quantitative result assertions in prose/figures. The "
        "paper-era release is a substantial framework: all 55 Python files compile, "
        "all three upstream tests pass, three released example seeds and a nine-task "
        "example bank execute deterministically, and 38/67 mechanism dimensions "
        "match or have meaningful analogues. These are components, not the paper "
        "experiment. The README explicitly excludes private market data, trained "
        "checkpoints, experiment logs, and paper-specific reproduction scripts; no "
        "paper factors, baselines, fusion arrays, trials, seeds, or costs are shipped, "
        "so 0/75 table cells count as native reproductions. The separate 3/3 grade-B "
        "component gate remains adapted and provides no paper-result credit.",
    ),
    "SYS-RD-AGENT-QUANT": (
        "N",
        "The snapshot provides the broad R&D-Agent framework and quant runners, "
        "but no bundled dated output from the R&D-Agent-Quant lineage.",
    ),
    "SYS-ALPHA-QUANTER": (
        "N",
        "A pinned paper audit checks all 790 numeric cells in Tables 5--8 and "
        "10--14. The release ships 2,615 training/validation prompt-label rows: "
        "a current Yahoo retrieval reproduces 523 labels exactly and 2,612 reward "
        "regimes. A released-semantics market-baseline reconstruction matches 1/34 "
        "repeated Buy-and-Hold cells at display precision. These are components, "
        "not agent outputs; all 756 non-market cells lack checkpoints, actions, "
        "three-seed paths, logs, or human ratings, and the paper test split is absent.",
    ),
    "SYS-CONTEST-TRADE": (
        "N",
        "A pinned arXiv-v4 audit enumerates all 49 numeric cells in Tables 1--3. "
        "The released CLI runs a three-node agent graph that never calls either "
        "paper contest and does not construct the Sharpe-weighted portfolio. The "
        "isolated Research Contest lacks both required models and a method it calls; "
        "the isolated Data Contest ships two fixed models without rolling-training "
        "provenance, uses top-3 sorting rather than facility-location allocation, and "
        "changes the paper's signed ZI sum into a clipped positive-only average. No "
        "native inputs, outputs, evaluator, baselines, ablations, or seeds are shipped, "
        "so zero paper result cells count as native reproductions.",
    ),
    "SYS-CRYPTO-TRADE": (
        "Y",
        "The README ships a dated one-step ETH action/ROI example. A pinned paper-level "
        "audit additionally recomputes 174/180 displayed deterministic traditional-baseline "
        "cells (43/45 complete rows) from the native crypto data and environment, but no "
        "full-period LLM or time-series result paths are shipped. The evidence remains "
        "crypto rather than six-country equity output.",
    ),
    "SYS-FIN-CON": (
        "N",
        "The reachable repository contains a single statically insufficient file "
        "and no dated native output.",
    ),
    "SYS-FIN-MEM": (
        "N",
        "A pinned paper audit recomputes 16/40 repeated Buy-and-Hold metric cells "
        "from the released formula and a current Yahoo snapshot, including both full "
        "TSLA ablation rows. All 195 non-Buy-and-Hold cells remain unverifiable: the "
        "release ships fake/sample inputs but no native action paths, checkpoints, or "
        "five-trial outputs, and its sole config differs from the paper.",
    ),
    "SYS-FIN-RL-DEEPSEEK": (
        "N",
        "The snapshot ships training/backtest code and points to external Nasdaq "
        "datasets; its README gives aggregate result descriptions but no dated "
        "native signal or return series.",
    ),
    "SYS-GURU-AGENTS": (
        "Y",
        "The snapshot bundles dated quarterly Nasdaq-100 portfolio CSVs, analysis "
        "logs, and backtest workbooks.  Coverage is U.S.-only and not the six-country "
        "common-task panel.",
    ),
    "SYS-MASS": (
        "N",
        "A pinned paper audit verifies a 242-day 2023 SSE50-like base/label panel and "
        "safely decodes a 263-date, 16-type learned distribution trajectory. This is "
        "native optimizer state, not a signal or return: all 277 numeric cells in "
        "Tables 1--4 remain unverifiable because decisions, other stock pools, "
        "baselines, backtests, and cost logs are not shipped.",
    ),
    "SYS-QUANT-AGENT-HFT": (
        "N",
        "A pinned arXiv-v4 audit checks all 272 numeric cells in Tables 1--2 and "
        "all 1,600 released benchmark CSVs. Every asset/horizon set has 100x100 "
        "rows and exact paper date endpoints, but the original 5,000-bar panels "
        "are absent. The paper-described recent-40-close LR reconstruction matches "
        "0/8 accuracies; all eight match only with an undocumented three-bar feature "
        "gap. No experiment evaluator, native predictions/risk ratios, baseline "
        "implementations, seeds/splits, portfolio paths, or numeric 1-hour paths "
        "are shipped, so zero paper result cells count as native reproductions.",
    ),
    "SYS-TRADING-AGENTS": (
        "N",
        "A pinned arXiv-v7 audit enumerates all 77 numeric cells in Table 1: 68 "
        "direct results and 9 derived improvements, plus 12 quantitative result "
        "claims in prose/figures. The nearest official source is v0.1.0, released "
        "about 52 hours after the paper; its parent contains only three site files. "
        "All 39 Python files compile and dependency-isolated native graph routing "
        "executes deterministically, while 14/45 paper mechanism dimensions match "
        "or have meaningful analogues. These are architecture components, not the "
        "paper experiment. No frozen multimodal data, exact config, backtest, "
        "portfolio/execution path, baselines, metrics, actions, fills, NAVs, returns, "
        "traces, seeds, or costs are shipped, so 0/77 table cells count as native "
        "reproductions. The paper itself has unresolved CR/AR formula, improvement, "
        "MDD-bound, and asset-universe inconsistencies.",
    ),
    "SYS-TRADING-R1": (
        "N",
        "The reachable repository is a one-file placeholder and contains no dated "
        "native output.",
    ),
}


TARGETED_EXECUTION = {
    "SYS-ALPHA-AGENT": "paper_audit:completed_zero_of_100_native_results_post_paper_rewrite",
    "SYS-ALPHA-MEMO": "paper_audit:completed_zero_of_474_native_results",
    "SYS-ALPHA-R1": "paper_audit:completed_zero_of_652_native_results_official_placeholder",
    "SYS-ALPHA-QUANTER": "paper_audit:completed_one_of_790_current_snapshot_buy_hold_match",
    "SYS-AUTOMATE-STRATEGY": "paper_audit:completed_zero_of_40_integrated_portfolio_cells_factor_component_only",
    "SYS-CONTEST-TRADE": "paper_audit:completed_zero_of_49_native_results",
    "SYS-CRYPTO-TRADE": "paper_audit:partial_174_of_468_traditional_baseline_cells",
    "SYS-FIN-CON": "legacy_targeted:blocked_jkp_scope_incompatible",
    "SYS-FIN-MEM": "paper_audit:completed_16_of_235_current_snapshot_buy_hold_matches",
    "SYS-GURU-AGENTS": "legacy_targeted:legacy_non_jkp_diagnostic_only",
    "SYS-MASS": "paper_audit:completed_zero_of_277_native_results_internal_state_only",
    "SYS-QUANT-AGENT-HFT": "paper_audit:completed_zero_of_272_native_results_undocumented_feature_gap",
    "SYS-QUANT-EVOLVER": "paper_audit:completed_zero_of_75_native_results_component_gate_separate",
    "SYS-QUANTA-ALPHA": "paper_audit:completed_zero_of_344_native_table_results_components_only",
    "SYS-RD-AGENT-QUANT": "legacy_targeted:blocked_on_jkp_adapter",
    "SYS-TRADING-AGENTS": "paper_audit:completed_zero_of_77_native_results",
    "SYS-TRADING-R1": "legacy_targeted:blocked_no_public_codebase",
}


OUTPUT_BLOCKS = {
    "SYS-AUTOMATE-STRATEGY": "A3_output_lacks_six_country_security_mapping",
    "SYS-CRYPTO-TRADE": "A3_wrong_asset_class_crypto",
    "SYS-GURU-AGENTS": "A3_US_only_not_six_country",
}


# The frozen static artifact audit used an over-broad "coming soon" heuristic:
# QuantaAlpha's roadmap for a separate future project demoted an otherwise
# complete code+environment+runner+config package to R1. The paper-level audit
# executes native components and justifies the corrected static package tier.
STATIC_TIER_OVERRIDES = {
    "SYS-QUANTA-ALPHA": "R3",
}


FIELDS = [
    "system_id",
    "native_task",
    "public_artifact_status",
    "static_tier",
    "native_dated_signal_or_return_shipped",
    "prespecified_G7_monthly_common_task_compatible",
    "blocking_stage",
    "evidence_url",
    "concise_evidence_note",
    "targeted_execution_audit_status",
    "fidelity_class",
]


def first_url(value: str) -> str:
    matches = URL_RE.findall(value or "")
    return matches[0] if matches else ""


def native_task(row: dict[str, str]) -> str:
    text = row["inclusion_exclusion_rationale"].strip()
    text = re.sub(r"^IN:\s*", "", text)
    return text.rstrip(".")


def main() -> None:
    with CENSUS.open(encoding="utf-8", newline="") as stream:
        census = list(csv.DictReader(stream, delimiter="|"))
    with AUDIT.open(encoding="utf-8", newline="") as stream:
        audit_rows = list(csv.DictReader(stream))
    audit = {row["system_id"]: row for row in audit_rows}

    ft = [row for row in census if row["stratum"] in {"F", "T"}]
    if len(ft) != EXPECTED_FT or len({row["system_id"] for row in ft}) != EXPECTED_FT:
        raise ValueError("frozen census must contain 67 unique F/T systems")
    if any(row["system_id"] not in audit for row in ft):
        raise ValueError("artifact audit does not cover every F/T system")

    output_rows = []
    for source in ft:
        sid = source["system_id"]
        observed = audit[sid]
        listed = observed["public_artifact_listed"] == "Y"
        reachability = observed["reachability_outcome"]

        if not listed:
            artifact_status = "not_listed"
            shipped = "N"
            block = "A0_no_public_artifact"
            fidelity = "F0_no_public_artifact"
            evidence = first_url(source["primary_record"])
            note = (
                f"The frozen primary record identifies {native_task(source)}; "
                "the registry lists no public artifact, so no native dated output "
                "was available for static inspection."
            )
        elif reachability == "check_failed":
            artifact_status = "listed_check_failed"
            shipped = "uncertain"
            block = "A1_artifact_access_unresolved"
            fidelity = "F0_artifact_unresolved"
            evidence = first_url(observed["artifact_urls"])
            note = (
                "The listed anonymous artifact returned HTTP 401 during the frozen "
                "audit; its package and any native outputs could not be resolved."
            )
        elif reachability == "unreachable_all":
            artifact_status = "listed_unreachable"
            shipped = "uncertain"
            block = "A1_artifact_access_unresolved"
            fidelity = "F0_artifact_unresolved"
            evidence = first_url(observed["artifact_urls"])
            note = (
                "The listed project page returned HTTP 404 during the frozen audit; "
                "its package and any native outputs could not be resolved."
            )
        else:
            artifact_status = "reachable_static_snapshot"
            evidence = first_url(observed["artifact_urls"])
            try:
                shipped, note = ARTIFACT_NOTES[sid]
            except KeyError as exc:
                raise ValueError(f"missing static artifact note for {sid}") from exc
            if shipped == "Y":
                block = OUTPUT_BLOCKS[sid]
                fidelity = "F2_dated_output_task_incompatible"
            else:
                block = "A2_no_shipped_native_dated_output"
                fidelity = "F1_static_no_native_output"

        output_rows.append(
            {
                "system_id": sid,
                "native_task": native_task(source),
                "public_artifact_status": artifact_status,
                "static_tier": STATIC_TIER_OVERRIDES.get(
                    sid, observed["static_fidelity_tier"]
                ),
                "native_dated_signal_or_return_shipped": shipped,
                "prespecified_G7_monthly_common_task_compatible": "N",
                "blocking_stage": block,
                "evidence_url": evidence,
                "concise_evidence_note": note,
                "targeted_execution_audit_status": TARGETED_EXECUTION.get(
                    sid, "not_targeted_in_legacy_execution_audit"
                ),
                "fidelity_class": fidelity,
            }
        )

    if len({row["system_id"] for row in output_rows}) != EXPECTED_FT:
        raise ValueError("output ledger does not contain 67 unique systems")
    if any(row["prespecified_G7_monthly_common_task_compatible"] != "N" for row in output_rows):
        raise ValueError("strict compatibility crosswalk unexpectedly contains a compatible row")

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    temporary = OUTPUT.with_suffix(".csv.tmp")
    with temporary.open("w", encoding="utf-8", newline="") as stream:
        writer = csv.DictWriter(
            stream, fieldnames=FIELDS, lineterminator="\n"
        )
        writer.writeheader()
        writer.writerows(output_rows)
    temporary.replace(OUTPUT)


if __name__ == "__main__":
    main()
